# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
          echo 'init script' # runs during prebuild
          pip install git+https://github.com/GNSSpy-Project/gnsspy
          pip install pyunpack
          pip install georinex
          pip install geopandas
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
